<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Vendor;
use App\Support\Audit;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
class UserController extends Controller {
 public function index(Request $r){$q=User::with('roles:id,name');$term=$r->string('search')->trim()->value();$q->when($term,fn($x)=>$x->where(fn($y)=>$y->where('name','like',"%{$term}%")->orWhere('email','like',"%{$term}%")->orWhere('username','like',"%{$term}%")))->when($r->account_type,fn($x,$v)=>$x->where('account_type',$v))->when($r->role,fn($x,$v)=>$x->role($v));if($r->status==='active')$q->where('is_blocked',false);elseif($r->status==='inactive')$q->where('is_blocked',true);if($r->verification==='verified')$q->whereNotNull('email_verified_at');elseif($r->verification==='unverified')$q->whereNull('email_verified_at');return response()->json($q->latest()->paginate(min((int)$r->input('per_page',20),100))->through(fn($u)=>$this->resource($u)));}
 public function show(User $user){return response()->json(['data'=>$this->resource($user)]);}
 public function store(Request $r){$d=$this->valid($r);$roles=$this->roles($r);$this->ensureAssignable($r,$roles);$invite=($d['onboarding']??'invite')==='invite';if(!$invite&&empty($d['password']))throw ValidationException::withMessages(['password'=>['Password is required.']]);return DB::transaction(function()use($r,$d,$roles,$invite){$user=User::create([...collect($d)->except(['roles','onboarding','vendor_id','assigned_vendor_ids','assigned_brand_ids','assigned_subcategory_ids','password_confirmation'])->all(),'password'=>$invite?Str::random(48):$d['password']]);$user->syncRoles($roles);$this->vendor($user,$d['vendor_id']??null);$this->assignedVendors($user,$d['assigned_vendor_ids']??[]);$this->assignedBrands($user,$d['assigned_brand_ids']??[]);$this->assignedSubcategories($user,$d['assigned_subcategory_ids']??[]);if($invite)$user->sendPasswordResetNotification(Password::createToken($user));Audit::record($r,'user.created',$user,null,$this->snap($user));return response()->json(['message'=>$invite?'User created and invitation sent.':'User created.','data'=>$this->resource($user)],201);});}
 public function update(Request $r,User $user){$d=$this->valid($r,$user);$before=$this->snap($user);$user->update(collect($d)->except(['roles','onboarding','vendor_id','assigned_vendor_ids','assigned_brand_ids','assigned_subcategory_ids','password','password_confirmation'])->all());$this->vendor($user,$d['vendor_id']??null);$this->assignedVendors($user,$d['assigned_vendor_ids']??[]);$this->assignedBrands($user,$d['assigned_brand_ids']??[]);$this->assignedSubcategories($user,$d['assigned_subcategory_ids']??[]);Audit::record($r,'user.updated',$user,$before,$this->snap($user));return response()->json(['message'=>'User updated.','data'=>$this->resource($user)]);}
 public function syncRoles(Request $r,User $user){$roles=$this->roles($r);$this->ensureAssignable($r,$roles);if($user->isSuperAdmin()&&!in_array('Super Admin',$roles,true)&&User::role('Super Admin')->where('is_blocked',false)->count()<=1)abort(422,'The last active Super Admin cannot lose that role.');$before=$this->snap($user);$user->syncRoles($roles);Audit::record($r,'user.roles_synced',$user,$before,$this->snap($user));return response()->json(['message'=>'Roles updated.','data'=>$this->resource($user)]);}
 public function status(Request $r,User $user){$d=$r->validate(['active'=>['required','boolean']]);abort_unless($r->user()->can($d['active']?'users.activate':'users.deactivate'),403);if(!$d['active']&&$user->isSuperAdmin()&&User::role('Super Admin')->where('is_blocked',false)->count()<=1)abort(422,'The last active Super Admin cannot be deactivated.');$before=$this->snap($user);$user->update(['is_blocked'=>!$d['active']]);if(!$d['active'])$user->tokens()->delete();Audit::record($r,$d['active']?'user.activated':'user.deactivated',$user,$before,$this->snap($user));return response()->json(['message'=>$d['active']?'User activated.':'User deactivated.','data'=>$this->resource($user)]);}
 public function invite(Request $r,User $user){$user->sendPasswordResetNotification(Password::createToken($user));Audit::record($r,'user.invitation_sent',$user);return response()->json(['message'=>'Invitation sent.']);}
 public function resetPassword(Request $r,User $user){$user->sendPasswordResetNotification(Password::createToken($user));Audit::record($r,'user.password_reset_sent',$user);return response()->json(['message'=>'Password reset sent.']);}
 private function valid(Request $r,?User $user=null){return $r->validate(['name'=>['required','string','max:100'],'username'=>['nullable','string','max:80','alpha_dash',Rule::unique('users')->ignore($user)],'email'=>['required','email','max:150',Rule::unique('users')->ignore($user)],'phone'=>['nullable','string','max:30'],'company_name'=>['nullable','string','max:150'],'address'=>['nullable','string','max:1000'],'city'=>['nullable','string','max:100'],'country'=>['nullable','string','max:100'],'account_type'=>['required',Rule::in(['staff','buyer','vendor'])],'vendor_id'=>['nullable','required_if:account_type,vendor','integer','exists:vendors,id'],'assigned_vendor_ids'=>['nullable','array'],'assigned_vendor_ids.*'=>['integer','distinct','exists:vendors,id'],'assigned_brand_ids'=>['nullable','array'],'assigned_brand_ids.*'=>['integer','distinct','exists:brands,id'],'assigned_subcategory_ids'=>['nullable','array'],'assigned_subcategory_ids.*'=>['integer','distinct',Rule::exists('categories','id')->whereNotNull('parent_id')],'onboarding'=>['nullable',Rule::in(['invite','password'])],'password'=>['nullable','string','min:8','confirmed'],'roles'=>['nullable','array','min:1'],'roles.*'=>['string','exists:roles,name']]);}
 private function roles(Request $r){return $r->validate(['roles'=>['required','array','min:1'],'roles.*'=>['string','distinct','exists:roles,name']])['roles'];}
 private function vendor(User $u,?int $id){if($u->account_type==='vendor')Vendor::whereKey($id)->update(['user_id'=>$u->id]);else Vendor::where('user_id',$u->id)->update(['user_id'=>null]);}
 private function assignedVendors(User $u,array $ids){$u->assignedVendors()->sync($u->account_type==='staff'?$ids:[]);}
 private function assignedBrands(User $u,array $ids){$u->assignedBrands()->sync($u->account_type==='staff'?$ids:[]);}
 private function assignedSubcategories(User $u,array $ids){$u->assignedSubcategories()->sync($u->account_type==='staff'?$ids:[]);}
 private function snap(User $u){$u=$u->fresh();return $u->only(['id','name','username','email','account_type','is_blocked'])+['roles'=>$u->getRoleNames()->all(),'assigned_vendor_ids'=>$u->assignedVendors()->pluck('vendors.id')->all(),'assigned_brand_ids'=>$u->assignedBrands()->pluck('brands.id')->all(),'assigned_subcategory_ids'=>$u->assignedSubcategories()->pluck('categories.id')->all()];}
 private function ensureAssignable(Request $r,array $roles){if($r->user()->isSuperAdmin())return;$requested=\Spatie\Permission\Models\Role::whereIn('name',$roles)->with('permissions:id,name')->get()->flatMap->permissions->pluck('name')->unique();abort_if($requested->diff($r->user()->getAllPermissions()->pluck('name'))->isNotEmpty(),403,'You cannot assign a role containing permissions you do not have.');}
 private function resource(User $u){$u->load('roles:id,name');$permissions=$u->getAllPermissions()->pluck('name')->values();$u->unsetRelation('permissions')->setAttribute('vendor_id',$u->vendorProfile()->value('id'));$u->setAttribute('assigned_vendor_ids',$u->assignedVendors()->pluck('vendors.id')->all());$u->setAttribute('assigned_brand_ids',$u->assignedBrands()->pluck('brands.id')->all());$u->setAttribute('assigned_subcategory_ids',$u->assignedSubcategories()->pluck('categories.id')->all());$u->setAttribute('permissions',$permissions);return $u;}
}
