<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BrandController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\IndustryController;
use App\Http\Controllers\Api\VendorController;
use App\Http\Controllers\Api\ServiceController;
use App\Http\Controllers\Api\DemoRequestController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\InventoryController;
use App\Http\Controllers\Api\CustomerController;
use App\Http\Controllers\Api\SalesLeadController;
use App\Http\Controllers\Api\ProjectController;
use App\Http\Controllers\Api\SpecificationController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\PermissionController;
use App\Http\Controllers\Api\AuditLogController;
use App\Http\Controllers\Api\MarketplaceBuilderController;
use App\Http\Controllers\Api\MarketplaceMediaController;
use App\Http\Controllers\Api\MarketplaceTemplateController;
use App\Http\Controllers\Api\SellingCountryController;
use App\Http\Controllers\Api\UserNotificationStateController;
use App\Http\Controllers\Api\DashboardController;
use Illuminate\Support\Facades\Route;

Route::post('auth/register', [AuthController::class, 'register'])->middleware('throttle:authentication');
Route::post('auth/register-vendor', [AuthController::class, 'registerVendor'])->middleware('throttle:authentication');
Route::post('auth/verify-email', [AuthController::class, 'verifyEmail'])->middleware('throttle:authentication');
Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:authentication');
Route::post('auth/forgot-password', [AuthController::class, 'forgotPassword'])->middleware('throttle:password-reset');
Route::post('auth/reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:password-reset');
Route::get('marketplace/services', [ServiceController::class, 'marketplace']);
Route::get('marketplace/services/{service}', [ServiceController::class, 'marketplaceShow']);
Route::get('marketplace/services/{service}/ratings', [ServiceController::class, 'ratings']);
Route::get('marketplace/categories', [CategoryController::class, 'marketplace']);
Route::get('marketplace/brands', [BrandController::class, 'marketplace']);
Route::get('marketplace/industries', [IndustryController::class, 'marketplace']);
Route::get('marketplace/selling-countries', [SellingCountryController::class, 'show']);
Route::get('marketplace/page', [MarketplaceBuilderController::class, 'publicPage']);
Route::get('marketplace/media/{asset}', [MarketplaceMediaController::class, 'show'])->withoutMiddleware('throttle:api')->middleware('throttle:marketplace-media');
Route::get('specifications', [SpecificationController::class, 'index']);

Route::middleware('auth:sanctum')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index']);
    Route::get('notification-states', [UserNotificationStateController::class, 'index']);
    Route::post('notification-states/read', [UserNotificationStateController::class, 'markRead']);
    Route::post('notification-states/clear', [UserNotificationStateController::class, 'clear']);
    Route::get('auth/user', [AuthController::class, 'user']);
    Route::patch('auth/profile', [AuthController::class, 'updateProfile']);
    Route::patch('auth/company', [AuthController::class, 'updateCompany']);
    Route::patch('auth/password', [AuthController::class, 'updatePassword']);
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::get('users', [UserController::class, 'index'])->middleware('permission:users.view');
    Route::post('users', [UserController::class, 'store'])->middleware('permission:users.create');
    Route::get('users/{user}', [UserController::class, 'show'])->middleware('permission:users.view');
    Route::put('users/{user}', [UserController::class, 'update'])->middleware('permission:users.update');
    Route::patch('users/{user}/roles', [UserController::class, 'syncRoles'])->middleware('permission:users.assign_roles');
    Route::patch('users/{user}/status', [UserController::class, 'status'])->middleware('permission:users.activate|users.deactivate');
    Route::post('users/{user}/invite', [UserController::class, 'invite'])->middleware('permission:users.send_invite');
    Route::post('users/{user}/reset-password', [UserController::class, 'resetPassword'])->middleware('permission:users.reset_password');
    Route::get('roles', [RoleController::class, 'index'])->middleware('permission:roles.view');
    Route::post('roles', [RoleController::class, 'store'])->middleware('permission:roles.create');
    Route::put('roles/{role}', [RoleController::class, 'update'])->middleware('permission:roles.update|roles.manage_permissions');
    Route::delete('roles/{role}', [RoleController::class, 'destroy'])->middleware('permission:roles.delete');
    Route::get('permissions', [PermissionController::class, 'index'])->middleware('permission:roles.view');
    Route::get('audit-logs', [AuditLogController::class, 'index'])->middleware('permission:audit_logs.view');
    Route::get('settings/selling-countries', [SellingCountryController::class, 'show'])->middleware('permission:services.view');
    Route::put('settings/selling-countries', [SellingCountryController::class, 'update'])->middleware('permission:settings.manage');
    Route::get('marketplace-builder', [MarketplaceBuilderController::class, 'show'])->middleware('permission:marketplace_builder.view');
    Route::put('marketplace-builder/draft', [MarketplaceBuilderController::class, 'saveDraft'])->middleware('permission:marketplace_builder.update');
    Route::post('marketplace-builder/publish', [MarketplaceBuilderController::class, 'publish'])->middleware('permission:marketplace_builder.publish');
    Route::post('marketplace-builder/schedule', [MarketplaceBuilderController::class, 'schedule'])->middleware('permission:marketplace_builder.publish');
    Route::get('marketplace-builder/versions', [MarketplaceBuilderController::class, 'versions'])->middleware('permission:marketplace_builder.view');
    Route::post('marketplace-builder/versions/{version}/restore', [MarketplaceBuilderController::class, 'restore'])->middleware('permission:marketplace_builder.update');
    Route::post('marketplace-builder/templates/default/reset', [MarketplaceBuilderController::class, 'resetToDefaultTemplate'])->middleware('permission:marketplace_builder.update');
    Route::post('marketplace-builder/templates/default/save', [MarketplaceBuilderController::class, 'saveDefaultTemplate'])->middleware('permission:marketplace_builder.update');
    Route::get('marketplace-builder/templates', [MarketplaceTemplateController::class, 'index'])->middleware('permission:marketplace_builder.view');
    Route::post('marketplace-builder/templates', [MarketplaceTemplateController::class, 'store'])->middleware('permission:marketplace_builder.update');
    Route::get('marketplace-builder/templates/{template}', [MarketplaceTemplateController::class, 'show'])->middleware('permission:marketplace_builder.view');
    Route::patch('marketplace-builder/templates/{template}', [MarketplaceTemplateController::class, 'update'])->middleware('permission:marketplace_builder.update');
    Route::post('marketplace-builder/templates/{template}/clone', [MarketplaceTemplateController::class, 'clone'])->middleware('permission:marketplace_builder.update');
    Route::post('marketplace-builder/templates/{template}/apply', [MarketplaceTemplateController::class, 'apply'])->middleware('permission:marketplace_builder.update');
    Route::delete('marketplace-builder/templates/{template}', [MarketplaceTemplateController::class, 'destroy'])->middleware('permission:marketplace_builder.update');
    Route::get('marketplace-builder/catalog', [MarketplaceBuilderController::class, 'catalog'])->middleware('permission:marketplace_builder.view');
    Route::get('marketplace-builder/media', [MarketplaceMediaController::class, 'index'])->middleware('permission:marketplace_builder.view');
    Route::post('marketplace-builder/media', [MarketplaceMediaController::class, 'store'])->middleware('permission:marketplace_builder.manage_media');
    Route::patch('marketplace-builder/media/{asset}', [MarketplaceMediaController::class, 'update'])->middleware('permission:marketplace_builder.manage_media');
    Route::delete('marketplace-builder/media/{asset}', [MarketplaceMediaController::class, 'archive'])->middleware('permission:marketplace_builder.manage_media');

    Route::post('categories', [CategoryController::class, 'store'])->middleware('permission:categories.create');
    Route::put('categories/{category}', [CategoryController::class, 'update'])->middleware('permission:categories.update');
    Route::delete('categories/{category}', [CategoryController::class, 'destroy'])->middleware('permission:categories.delete');
    Route::get('categories', [CategoryController::class, 'index'])->middleware('permission:categories.view');
    Route::get('brands', [BrandController::class, 'index'])->middleware('permission:brands.view');
    Route::post('brands', [BrandController::class, 'store'])->middleware('permission:brands.create');
    Route::put('brands/{brand}', [BrandController::class, 'update'])->middleware('permission:brands.update');
    Route::delete('brands/{brand}', [BrandController::class, 'destroy'])->middleware('permission:brands.delete');
    Route::post('brands/{brand}/approve', [BrandController::class, 'approve'])->middleware('permission:brands.approve');
    Route::get('industries', [IndustryController::class, 'index'])->middleware('permission:industries.view');
    Route::post('industries', [IndustryController::class, 'store'])->middleware('permission:industries.create');
    Route::put('industries/{industry}', [IndustryController::class, 'update'])->middleware('permission:industries.update');
    Route::delete('industries/{industry}', [IndustryController::class, 'destroy'])->middleware('permission:industries.delete');
    Route::get('customers', [CustomerController::class, 'index'])->middleware('permission:customers.view');
    Route::get('sales-leads', [SalesLeadController::class, 'index'])->middleware('permission:customers.view');
    Route::get('sales-leads/buyers/search', [SalesLeadController::class, 'buyers'])->middleware('permission:customers.view');
    Route::post('sales-leads', [SalesLeadController::class, 'store'])->middleware('permission:customers.view');
    Route::patch('sales-leads/{salesLead}', [SalesLeadController::class, 'update'])->middleware('permission:customers.view');
    Route::get('projects', [ProjectController::class, 'index'])->middleware('permission:customers.view');
    Route::post('projects', [ProjectController::class, 'store'])->middleware('permission:customers.view');
    Route::patch('projects/{project}', [ProjectController::class, 'update'])->middleware('permission:customers.view');
    Route::patch('customers/{customer}/crm', [CustomerController::class, 'updateCrm'])->middleware('permission:customers.assign|customers.follow_up');
    Route::patch('customers/{customer}/blocked', [CustomerController::class, 'setBlocked'])->middleware('permission:customers.block|customers.unblock');
    Route::get('vendors', [VendorController::class, 'index'])->middleware('permission:vendors.view');
    Route::post('vendors', [VendorController::class, 'store'])->middleware('permission:vendors.create');
    Route::put('vendors/{vendor}', [VendorController::class, 'update'])->middleware('permission:vendors.update');
    Route::post('vendors/{vendor}/approve', [VendorController::class, 'approve'])->middleware('permission:vendors.approve');
    Route::delete('vendors/{vendor}', [VendorController::class, 'destroy'])->middleware('permission:vendors.delete');
    Route::post('vendors/{vendor}/impersonate', [AuthController::class, 'impersonateVendor'])->middleware('permission:vendors.impersonate');
    Route::get('services', [ServiceController::class, 'index'])->middleware('permission:services.view');
    Route::post('services', [ServiceController::class, 'store'])->middleware('permission:services.create');
    Route::patch('services/{service}', [ServiceController::class, 'update'])->middleware('permission:services.update');
    Route::put('services/{service}/product', [ServiceController::class, 'updateProduct'])->middleware('permission:services.update');
    Route::delete('services/{service}/product', [ServiceController::class, 'destroyProduct'])->middleware('permission:services.delete');
    Route::delete('services/{service}', [ServiceController::class, 'destroy'])->middleware('permission:services.delete');
    Route::post('specifications', [SpecificationController::class, 'store'])->middleware('permission:specifications.create');
    Route::put('specifications/{specification}', [SpecificationController::class, 'update'])->middleware('permission:specifications.update');
    Route::delete('specifications/{specification}', [SpecificationController::class, 'destroy'])->middleware('permission:specifications.delete');
    Route::patch('demo-requests/{demoRequest}', [DemoRequestController::class, 'update'])->middleware('permission:demos.update');
    Route::patch('demo-requests/{demoRequest}/moderation', [DemoRequestController::class, 'moderate'])->middleware('permission:demos.moderate');
    Route::patch('purchase-orders/{purchaseOrder}/assign-vendor', [DemoRequestController::class, 'assignPurchaseOrderVendor'])->middleware('permission:purchase_orders.assign_vendor');
    Route::post('demo-requests', [DemoRequestController::class, 'store']);
    Route::post('marketplace/services/{service}/ratings', [ServiceController::class, 'rate']);
    Route::get('demo-requests', [DemoRequestController::class, 'index'])->middleware('permission:demos.view');
    Route::get('quote-requests', [DemoRequestController::class, 'quoteIndex'])->middleware('permission:rfqs.view');
    Route::get('quote-requests/{demoRequest}/buyer-attachment', [DemoRequestController::class, 'downloadBuyerAttachment'])->middleware('permission:rfqs.view');
    Route::get('quote-requests/{demoRequest}/vendor-attachment', [DemoRequestController::class, 'downloadVendorQuoteAttachment'])->middleware('permission:rfqs.view');
    Route::post('quote-requests/{demoRequest}/send', [DemoRequestController::class, 'sendQuote'])->middleware('permission:rfqs.quote');
    Route::post('quote-requests/{demoRequest}/respond', [DemoRequestController::class, 'respondToQuote'])->middleware('permission:rfqs.respond');
    Route::post('quote-requests/{demoRequest}/purchase-order', [DemoRequestController::class, 'generatePurchaseOrder'])->middleware('permission:purchase_orders.create');
    Route::post('quote-requests/{demoRequest}/purchase-order/send', [DemoRequestController::class, 'sendPurchaseOrder'])->middleware('permission:purchase_orders.send');
    Route::get('purchase-orders', [DemoRequestController::class, 'purchaseOrdersIndex'])->middleware('permission:purchase_orders.view');
    Route::get('orders', [OrderController::class, 'index']);
    Route::post('orders', [OrderController::class, 'store']);
    Route::patch('orders/{order}/status', [OrderController::class, 'updateStatus']);
    Route::patch('orders/{order}/payment', [OrderController::class, 'updatePayment']);
    Route::get('inventory', [InventoryController::class, 'index']);
    Route::patch('inventory/{service}', [InventoryController::class, 'update']);
    Route::post('demo-notifications/read', [DemoRequestController::class, 'markBuyerNotificationsRead']);
    Route::get('demo-requests/{demoRequest}/messages', [DemoRequestController::class, 'messages'])->middleware('permission:messages.view');
    Route::post('demo-requests/{demoRequest}/messages', [DemoRequestController::class, 'sendMessage'])->middleware('permission:messages.send');
});

Route::get('categories/{category}/logo', [CategoryController::class, 'logo'])->withoutMiddleware('throttle:api')->middleware('throttle:marketplace-media');
Route::get('brands/{brand}/logo', [BrandController::class, 'logo'])->withoutMiddleware('throttle:api')->middleware('throttle:marketplace-media');
Route::get('industries/{industry}/logo', [IndustryController::class, 'logo'])->withoutMiddleware('throttle:api')->middleware('throttle:marketplace-media');
Route::get('vendors/{vendor}/document', [VendorController::class, 'document'])->withoutMiddleware('throttle:api')->middleware('throttle:marketplace-media');
Route::get('vendors/{vendor}/logo', [VendorController::class, 'logo'])->withoutMiddleware('throttle:api')->middleware('throttle:marketplace-media');
Route::get('marketplace/service-images/{serviceImage}', [ServiceController::class, 'marketplaceImage'])->withoutMiddleware('throttle:api')->middleware('throttle:marketplace-media');
