import { ChevronDown, Facebook, Linkedin, Youtube } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import BrandLogo from '../common/BrandLogo'

const columns = { Solutions: ['ERP','CRM','HRMS','Cloud Computing','Cyber Security','AI Solutions','View All'], Brands: ['Microsoft','AWS','SAP','Oracle','Google Cloud','VMware','View All'], Industries: ['Healthcare','Manufacturing','Education','Retail','Finance','Real Estate','View All'], Resources: ['Buying Guides','Comparisons','Whitepapers','Blog','ROI Calculator'], Company: ['About Us','Careers','Contact Us','Press'], Support: ['Help Center','Contact Support','Terms & Conditions','Privacy Policy'] }
function FooterColumn({ title, links }) { const [open,setOpen] = useState(false); return <section className="border-b py-1 md:border-0 md:py-0"><button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between py-2 text-left text-xs font-bold md:pointer-events-none md:py-0"><span>{title}</span><ChevronDown className={`h-4 w-4 transition md:hidden ${open ? 'rotate-180' : ''}`}/></button><ul className={`${open ? 'block' : 'hidden'} space-y-1.5 pb-3 md:block md:pt-3`} >{links.map((link) => <li key={link}>{title === 'Solutions' && link === 'View All' ? <Link to="/services" className="text-[11px] font-semibold text-primary hover:underline">View All</Link> : <a href="#" className="text-[11px] text-slate-500 hover:text-primary">{link}</a>}</li>)}</ul></section> }
export default function Footer() {
  const [email,setEmail] = useState(''); const [error,setError] = useState(''); const [success,setSuccess] = useState(false)
  const submit = (event) => { event.preventDefault(); if (!/^\S+@\S+\.\S+$/.test(email)) { setError('Enter a valid email address.'); return } setError(''); setEmail(''); setSuccess(true); setTimeout(() => setSuccess(false), 2500) }
  return <footer className="marketplace-footer relative border-t bg-white px-5 py-6 lg:px-6">
    <div className="grid gap-7 xl:grid-cols-[1.5fr_3.6fr_1.35fr]">
      <div><BrandLogo/><p className="mt-3 max-w-[260px] text-[11px] leading-5 text-slate-500">Your trusted marketplace to discover, compare and connect with the best technology solutions and partners.</p><div className="mt-4 flex gap-2">{[Linkedin,Facebook,({className}) => <span className={className}>X</span>,Youtube].map((Icon,index) => <a href="#" aria-label={['LinkedIn','Facebook','X','YouTube'][index]} key={index} className="grid h-7 w-7 place-items-center rounded-full border text-slate-500 hover:border-primary hover:text-primary"><Icon className="h-3.5 w-3.5 text-[11px] font-bold"/></a>)}</div></div>
      <div className="grid gap-x-5 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-6">{Object.entries(columns).map(([title,links]) => <FooterColumn key={title} title={title} links={links}/>)}</div>
      <form onSubmit={submit} className="self-start rounded-lg border p-4"><h3 className="text-sm font-bold">Stay Updated</h3><p className="mt-1.5 text-[11px] leading-4 text-slate-500">Get the latest updates, product news and offers delivered to your inbox.</p><label htmlFor="newsletter" className="sr-only">Email address</label><input id="newsletter" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-3 h-9 w-full rounded-md border px-3 text-xs" placeholder="Email address" type="email" aria-invalid={Boolean(error)}/>{error && <p className="mt-1 text-[11px] text-red-600">{error}</p>}<button className="mt-2 h-9 w-full rounded-md bg-primary text-xs font-semibold text-white hover:bg-blue-700">Subscribe</button></form>
    </div><div className="mt-6 border-t pt-4 text-right text-[11px] text-slate-500">© 2026 Quotation Global. All rights reserved.</div>{success && <div role="status" className="fixed bottom-5 right-5 z-50 rounded-md bg-slate-900 px-4 py-3 text-xs text-white shadow-lg">Thanks for subscribing.</div>}
  </footer>
}
