import { Bell, CheckCheck, FileCheck2, FileText, X } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { getDemoRequests } from '../../api/demoRequests'
import { clearNotifications, getNotificationStates, markNotificationsRead } from '../../api/notifications'
import { getQuoteRequests } from '../../api/rfqs'
import NotificationBadge from '../common/NotificationBadge'
import { startVisiblePolling } from '../../utils/visiblePolling'

const eventTime = (item) => item.purchase_order?.sent_at || item.buyer_quote_response_at || item.quoted_at || item.updated_at || item.created_at
const eventKey = (prefix, item) => `${prefix}:${item.id}:${item.status}:${eventTime(item) || 'unknown'}`.replace(/[^a-z0-9:_-]/gi, '-')

export default function PortalActivityActions({ isAdmin }) {
  const navigate = useNavigate(); const root = useRef(null)
  const [quotes, setQuotes] = useState([]); const [demos, setDemos] = useState([]); const [states, setStates] = useState({}); const [panel, setPanel] = useState(null); const [busy, setBusy] = useState(false)
  const load = () => Promise.all([getQuoteRequests(), getDemoRequests(), getNotificationStates()]).then(([quoteRows, demoRows, stateRows]) => { setQuotes(quoteRows); setDemos(demoRows.data || []); setStates(Object.fromEntries((stateRows.data || []).map((state) => [state.notification_key, state]))) }).catch(() => {})

  useEffect(() => { let active = true; const refresh = () => { if (active) load() }; const stopPolling = startVisiblePolling(refresh, 30000); return () => { active = false; stopPolling() } }, [])
  useEffect(() => { if (!panel) return undefined; const outside = (event) => { if (!root.current?.contains(event.target)) setPanel(null) }; const escape = (event) => { if (event.key === 'Escape') setPanel(null) }; document.addEventListener('mousedown', outside); document.addEventListener('keydown', escape); return () => { document.removeEventListener('mousedown', outside); document.removeEventListener('keydown', escape) } }, [panel])

  const activities = useMemo(() => [...quotes.map((item) => ({ key: eventKey('rfq', item), path: '/rfqs', type: 'rfq', title: item.purchase_order?.status === 'sent' ? 'Purchase order sent' : item.status === 'quote_accepted' ? 'Quote accepted' : item.status === 'quote_declined' ? 'Quote declined' : item.status === 'quoted' ? 'Vendor sent a quote' : 'New RFQ received', detail: `${item.service?.name || 'Product'} · ${item.user?.name || 'Customer'} · ${item.vendor?.company_name || item.vendor?.name || 'Vendor'}`, time: eventTime(item), po: item.purchase_order?.status === 'sent' })), ...demos.map((item) => ({ key: eventKey('demo', item), path: '/demos', type: 'demo', title: item.status === 'accepted' ? 'Demo accepted' : item.status === 'rejected' ? 'Demo rejected' : 'New demo request', detail: `${item.service?.name || 'Product'} · ${item.user?.name || 'Customer'} · ${item.vendor?.company_name || item.vendor?.name || 'Vendor'}`, time: eventTime(item), po: false }))].sort((a, b) => new Date(b.time) - new Date(a.time)).slice(0, 50).map((item) => ({ ...item, read: Boolean(states[item.key]?.read_at), cleared: Boolean(states[item.key]?.cleared_at) })), [quotes, demos, states])
  const visible = activities.filter((item) => !item.cleared); const rfqs = visible.filter((item) => item.type === 'rfq'); const unread = visible.filter((item) => !item.read).length; const unreadRfqs = rfqs.filter((item) => !item.read).length; const current = panel === 'rfqs' ? rfqs : visible

  const updateState = async (keys, action) => {
    if (!keys.length || busy) return; setBusy(true)
    try { await (action === 'clear' ? clearNotifications(keys) : markNotificationsRead(keys)); const now = new Date().toISOString(); setStates((existing) => ({ ...existing, ...Object.fromEntries(keys.map((key) => [key, { ...existing[key], notification_key: key, [action === 'clear' ? 'cleared_at' : 'read_at']: now }])) })) } finally { setBusy(false) }
  }
  const openPanel = (name) => setPanel((currentPanel) => currentPanel === name ? null : name)
  const openItem = async (item) => { if (!item.read) await updateState([item.key], 'read'); setPanel(null); navigate(item.path) }

  return <div ref={root} className="relative flex items-center gap-1.5">
    <button type="button" onClick={() => openPanel('rfqs')} className={`hidden items-center gap-1.5 rounded-md px-2 py-2 text-slate-600 transition hover:bg-blue-50 hover:text-primary focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 sm:flex ${panel === 'rfqs' ? 'bg-blue-50 text-primary' : ''}`} aria-expanded={panel === 'rfqs'} aria-haspopup="menu" title="RFQ notifications"><span className="relative"><FileText className="h-[18px] w-[18px]"/>{unreadRfqs > 0 && <NotificationBadge count={unreadRfqs}/>}</span><span className="hidden text-[11px] font-medium xl:inline">RFQs</span></button>
    <button type="button" onClick={() => openPanel('all')} className={`relative rounded-md p-2 text-slate-600 transition hover:bg-blue-50 hover:text-primary focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 ${panel === 'all' ? 'bg-blue-50 text-primary' : ''}`} aria-expanded={panel === 'all'} aria-haspopup="menu" aria-label={`Activity notifications${unread ? `, ${unread} new` : ''}`}><Bell className="h-[19px] w-[19px]"/>{unread > 0 && <NotificationBadge count={unread}/>}</button>
    {panel && <div role="menu" className="absolute right-0 top-11 z-50 w-[min(410px,calc(100vw-24px))] overflow-hidden rounded-xl border bg-white shadow-overlay">
      <div className="flex items-start justify-between gap-3 border-b px-4 py-3"><div><p className="text-sm font-bold text-slate-900">{panel === 'rfqs' ? 'RFQ Notifications' : isAdmin ? 'Platform Activity' : 'Vendor Activity'}</p><p className="mt-0.5 text-[11px] text-slate-500">{panel === 'rfqs' ? `${unreadRfqs} unread RFQ update${unreadRfqs === 1 ? '' : 's'}` : 'Live customer, quote, demo and PO updates'}</p></div><div className="flex items-center gap-1">{current.some((item) => !item.read) && <button disabled={busy} type="button" onClick={() => updateState(current.filter((item) => !item.read).map((item) => item.key), 'read')} className="rounded-md px-2 py-1.5 text-[11px] font-semibold text-primary hover:bg-blue-50 disabled:opacity-50"><CheckCheck className="mr-1 inline h-3.5 w-3.5"/>Read all</button>}{current.length > 0 && <button disabled={busy} type="button" onClick={() => updateState(current.map((item) => item.key), 'clear')} className="rounded-md px-2 py-1.5 text-[11px] font-semibold text-red-600 hover:bg-red-50 disabled:opacity-50">Clear all</button>}</div></div>
      <div className="max-h-[430px] overflow-y-auto">{current.map((item) => <div key={item.key} className={`group relative flex border-b last:border-0 ${item.read ? 'bg-white' : 'bg-blue-50/60'}`}><button type="button" onClick={() => openItem(item)} className="flex min-w-0 flex-1 gap-3 px-4 py-3 text-left hover:bg-slate-50"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${item.po ? 'bg-emerald-50 text-emerald-600' : 'bg-blue-50 text-primary'}`}>{item.po ? <FileCheck2 className="h-4 w-4"/> : <FileText className="h-4 w-4"/>}</span><span className="min-w-0 pr-5"><span className="flex items-center gap-2"><b className="block text-xs text-slate-900">{item.title}</b>{!item.read && <span className="h-2 w-2 shrink-0 rounded-full bg-primary"/>}</span><span className="mt-1 block truncate text-[11px] text-slate-500">{item.detail}</span><span className="mt-1 block text-[11px] text-slate-400">{item.time ? new Date(item.time).toLocaleString() : ''}</span></span></button><button type="button" disabled={busy} onClick={() => updateState([item.key], 'clear')} className="absolute right-2 top-2 grid h-7 w-7 place-items-center rounded-md text-slate-400 opacity-0 hover:bg-red-50 hover:text-red-600 focus:opacity-100 group-hover:opacity-100" aria-label={`Clear ${item.title}`}><X className="h-3.5 w-3.5"/></button></div>)}{!current.length && <div className="p-9 text-center"><Bell className="mx-auto h-7 w-7 text-slate-300"/><p className="mt-3 text-xs font-semibold text-slate-600">You're all caught up</p><p className="mt-1 text-[11px] text-slate-400">New updates will appear here.</p></div>}</div>
      {panel === 'rfqs' && <button type="button" onClick={() => { setPanel(null); navigate('/rfqs') }} className="w-full border-t px-4 py-3 text-xs font-semibold text-primary hover:bg-blue-50">View all RFQs</button>}
    </div>}
  </div>
}
