import { Bell, FileCheck2, FileText } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { getDemoRequests } from '../../api/demoRequests'
import { getQuoteRequests } from '../../api/rfqs'
import NotificationBadge from '../common/NotificationBadge'

export default function PortalActivityActions({ isAdmin }) {
  const navigate = useNavigate(); const root = useRef(null)
  const [quotes, setQuotes] = useState([]); const [demos, setDemos] = useState([]); const [open, setOpen] = useState(false)
  const key = isAdmin ? 'admin-activity-seen-at' : 'vendor-activity-seen-at'
  const [seenAt, setSeenAt] = useState(() => Number(localStorage.getItem(key) || 0))
  useEffect(() => { let active = true; const load = () => Promise.all([getQuoteRequests(), getDemoRequests()]).then(([quoteRows, demoRows]) => { if (active) { setQuotes(quoteRows); setDemos(demoRows.data || []) } }).catch(() => {}); load(); const timer = setInterval(load, 15000); return () => { active = false; clearInterval(timer) } }, [])
  useEffect(() => { if (!open) return undefined; const outside = (event) => { if (!root.current?.contains(event.target)) setOpen(false) }; document.addEventListener('mousedown', outside); return () => document.removeEventListener('mousedown', outside) }, [open])
  const activities = useMemo(() => [...quotes.map((item) => ({ id: `q-${item.id}`, path: '/rfqs', title: item.purchase_order?.status === 'sent' ? 'Purchase order sent' : item.status === 'quote_accepted' ? 'Quote accepted' : item.status === 'quote_declined' ? 'Quote declined' : item.status === 'quoted' ? 'Vendor sent a quote' : 'New RFQ received', detail: `${item.service?.name || 'Product'} · ${item.user?.name || 'Customer'} · ${item.vendor?.company_name || item.vendor?.name || 'Vendor'}`, time: item.purchase_order?.sent_at || item.buyer_quote_response_at || item.quoted_at || item.created_at, po: item.purchase_order?.status === 'sent' })), ...demos.map((item) => ({ id: `d-${item.id}`, path: '/demos', title: item.status === 'accepted' ? 'Demo accepted' : item.status === 'rejected' ? 'Demo rejected' : 'New demo request', detail: `${item.service?.name || 'Product'} · ${item.user?.name || 'Customer'} · ${item.vendor?.company_name || item.vendor?.name || 'Vendor'}`, time: item.updated_at || item.created_at, po: false }))].sort((a, b) => new Date(b.time) - new Date(a.time)).slice(0, 20), [quotes, demos])
  const unread = activities.filter((item) => new Date(item.time).getTime() > seenAt).length
  const rfqCount = quotes.filter((item) => ['pending', 'quoted'].includes(item.status)).length
  const toggle = () => { const next = !open; setOpen(next); if (next) { const now = Date.now(); setSeenAt(now); localStorage.setItem(key, String(now)) } }
  return <><button type="button" onClick={() => navigate('/rfqs')} className="hidden items-center gap-1.5 rounded-md px-1.5 py-2 text-slate-600 hover:bg-slate-50 sm:flex" title="Open RFQs"><span className="relative"><FileText className="h-[18px] w-[18px]"/><NotificationBadge count={rfqCount}/></span><span className="hidden text-[11px] font-medium xl:inline">RFQs</span></button><div ref={root} className="relative"><button type="button" onClick={toggle} className="relative rounded-md p-2 text-slate-600 hover:bg-slate-50" aria-label={`Activity notifications${unread ? `, ${unread} new` : ''}`}><Bell className="h-[19px] w-[19px]"/><NotificationBadge count={unread}/></button>{open && <div className="absolute right-0 top-11 z-50 w-[min(410px,calc(100vw-24px))] overflow-hidden rounded-xl border bg-white shadow-overlay"><div className="border-b px-4 py-3"><p className="text-sm font-bold text-slate-900">{isAdmin ? 'Platform Activity' : 'Vendor Activity'}</p><p className="mt-0.5 text-[11px] text-slate-500">Live customer, quote, demo and PO updates</p></div><div className="max-h-[430px] overflow-y-auto">{activities.map((item) => <button type="button" key={item.id} onClick={() => { setOpen(false); navigate(item.path) }} className="flex w-full gap-3 border-b px-4 py-3 text-left last:border-0 hover:bg-slate-50"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${item.po ? 'bg-emerald-50 text-emerald-600' : 'bg-blue-50 text-primary'}`}>{item.po ? <FileCheck2 className="h-4 w-4"/> : <FileText className="h-4 w-4"/>}</span><span className="min-w-0"><b className="block text-xs text-slate-900">{item.title}</b><span className="mt-1 block truncate text-[11px] text-slate-500">{item.detail}</span><span className="mt-1 block text-[11px] text-slate-400">{item.time ? new Date(item.time).toLocaleString() : ''}</span></span></button>)}{!activities.length && <p className="p-8 text-center text-xs text-slate-500">No activity yet.</p>}</div></div>}</div></>
}
