import { Eye, EyeOff, KeyRound, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { updateMyPassword } from '../api/auth'
import { useAuth } from '../auth/useAuth'
import AccountNavigation from '../components/account/AccountNavigation'
import { Alert, Button, Card, FieldError, PageHeader } from '../components/ui'

export default function AccountSettingsPage() {
  const { user } = useAuth(); const [form, setForm] = useState({ current_password: '', password: '', password_confirmation: '' }); const [show, setShow] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  const mismatch = form.password_confirmation && form.password !== form.password_confirmation ? 'Passwords do not match.' : ''
  const save = async (event) => { event.preventDefault(); if (mismatch) return; setSaving(true); setError(''); setMessage(''); try { const result = await updateMyPassword(form); setMessage(result.message); setForm({ current_password: '', password: '', password_confirmation: '' }) } catch (err) { setError(err.message) } finally { setSaving(false) } }
  const PasswordField = ({ label, name }) => <label className="block text-xs font-semibold text-slate-700">{label}<span className="relative mt-1.5 block"><input required minLength={name === 'current_password' ? undefined : 8} type={show ? 'text' : 'password'} autoComplete={name === 'current_password' ? 'current-password' : 'new-password'} value={form[name]} onChange={(event) => set(name, event.target.value)} className="h-11 w-full rounded-lg border bg-white px-3 pr-11 text-sm font-normal outline-none focus:border-primary focus:ring-2 focus:ring-primary/10"/><button type="button" onClick={() => setShow((current) => !current)} className="absolute right-1 top-0 grid h-11 w-10 place-items-center text-slate-400 hover:text-slate-700" aria-label={show ? 'Hide passwords' : 'Show passwords'}>{show ? <EyeOff className="h-4 w-4"/> : <Eye className="h-4 w-4"/>}</button></span>{name === 'password_confirmation' && <FieldError>{mismatch}</FieldError>}</label>
  return <section><PageHeader eyebrow="Account" title="Account Settings" description="Manage sign-in security and review your account status."/><div className="mt-6 grid gap-5 lg:grid-cols-[220px_minmax(0,720px)]"><AccountNavigation/><div className="space-y-5"><Card className="flex items-start gap-4 p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><ShieldCheck className="h-5 w-5"/></span><div><h2 className="text-sm font-semibold">Account security</h2><p className="mt-1 text-xs leading-5 text-slate-500">Signed in as {user?.email}. Changing your password signs out all other active sessions.</p></div></Card><Card className="p-5 sm:p-6"><div className="flex items-center gap-3"><KeyRound className="h-5 w-5 text-primary"/><div><h2 className="text-base font-semibold">Change password</h2><p className="mt-1 text-xs text-slate-500">Use at least 8 characters and avoid reused passwords.</p></div></div>{error && <Alert className="mt-4">{error}</Alert>}{message && <Alert tone="success" className="mt-4">{message}</Alert>}<form onSubmit={save} className="mt-5 space-y-4"><PasswordField label="Current password" name="current_password"/><PasswordField label="New password" name="password"/><PasswordField label="Confirm new password" name="password_confirmation"/><div className="flex justify-end border-t pt-4"><Button type="submit" loading={saving} disabled={Boolean(mismatch)}>Update password</Button></div></form></Card></div></div></section>
}
