import { Check, Minus, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { getMarketplaceServices } from '../api/marketplace'
import { getSpecifications } from '../api/specifications'

export default function ComparePage() {
  const [services, setServices] = useState([]); const [selected, setSelected] = useState([]); const [allDefinitions, setAllDefinitions] = useState([]); const [differences, setDifferences] = useState(false)
  useEffect(() => { getMarketplaceServices().then((rows) => { const grouped = Object.values(rows.reduce((all, item) => { const key = `${item.vendor_id}|${item.name}|${item.service_type}`; if (!all[key]) all[key] = { ...item, plans: [] }; all[key].plans.push(item); return all }, {})); setServices(grouped); const stored = JSON.parse(localStorage.getItem('compare-services') || '[]'); setSelected(grouped.filter((item) => stored.includes(item.id)).slice(0, 3)) }) }, [])
  const eligible = services.filter((item) => !selected.some((chosen) => chosen.id === item.id) && (!selected.length || (item.service_type === selected[0].service_type && String(item.subcategory_id) === String(selected[0].subcategory_id))))
  const add = (id) => { const item = services.find((row) => String(row.id) === String(id)); if (!item || selected.length >= 3) return; const next = [...selected, item]; setSelected(next); localStorage.setItem('compare-services', JSON.stringify(next.map((row) => row.id))) }
  const remove = (id) => { const next = selected.filter((item) => item.id !== id); setSelected(next); localStorage.setItem('compare-services', JSON.stringify(next.map((row) => row.id))) }
  useEffect(() => { if (!selected.length) return setAllDefinitions([]); getSpecifications({ service_type: selected[0].service_type, category_id: selected[0].category_id, subcategory_id: selected[0].subcategory_id }).then((result) => setAllDefinitions(result.data || [])).catch(() => setAllDefinitions([])) }, [selected])
  const definitions = useMemo(() => allDefinitions.filter((item) => item.is_comparable).sort((a, b) => a.sort_order - b.sort_order), [allDefinitions])
  const valueFor = (service, definition) => service.specification_values?.find((item) => item.specification_definition_id === definition.id)?.value || ''
  const rows = differences ? definitions.filter((definition) => new Set(selected.map((service) => valueFor(service, definition))).size > 1) : definitions
  const display = (value, definition) => { if (!value) return definition.field_type === 'boolean' ? <X className="mx-auto h-5 w-5 text-red-500"/> : <Minus className="mx-auto h-5 w-5 text-slate-300"/>; if (definition.field_type === 'boolean') return value === 'yes' ? <Check className="mx-auto h-5 w-5 text-emerald-600"/> : value === 'no' ? <X className="mx-auto h-5 w-5 text-red-500"/> : <span className="text-slate-400">N/A</span>; if (definition.field_type === 'duration') { try { const duration = JSON.parse(value); return <span>{duration.amount} {duration.unit}</span> } catch { return <span>{value}</span> } } return <span>{value}{definition.unit ? ` ${definition.unit}` : ''}</span> }
  return <section className="pb-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Smart comparison</p><h1 className="mt-1 text-2xl font-bold">Compare solutions</h1><p className="mt-1 text-sm text-slate-500">Select up to 3 products from the same type and subcategory.</p></div><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={differences} onChange={(e) => setDifferences(e.target.checked)}/>Show differences only</label></div><div className="mt-5 flex flex-wrap gap-3">{selected.map((item) => <span key={item.id} className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm font-semibold">{item.name}<button onClick={() => remove(item.id)}><X className="h-4 w-4 text-red-500"/></button></span>)}{selected.length < 3 && <select value="" onChange={(e) => add(e.target.value)} className="h-10 min-w-64 rounded-lg border bg-white px-3 text-sm"><option value="">+ Select product</option>{eligible.map((item) => <option key={item.id} value={item.id}>{item.name} — {item.vendor?.company_name}</option>)}</select>}</div>{selected.length < 2 ? <div className="mt-6 rounded-xl border border-dashed bg-white p-12 text-center text-sm text-slate-500">Select at least two matching products to compare.</div> : <div className="mt-6 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="w-52 p-4">Specification</th>{selected.map((item) => <th key={item.id} className="p-4 text-center"><div className="font-bold">{item.name}</div><div className="mt-1 text-xs font-normal text-slate-500">{item.vendor?.company_name || item.vendor?.name}</div></th>)}</tr></thead><tbody><tr className="border-t bg-blue-50/50"><th className="p-4">Starting price</th>{selected.map((item) => <td key={item.id} className="p-4 text-center font-bold text-primary">${Math.min(...item.plans.map((plan) => Number(plan.price_from))).toLocaleString()}</td>)}</tr><tr className="border-t"><th className="p-4">AI enabled</th>{selected.map((item) => <td key={item.id} className="p-4 text-center">{item.ai_enabled ? <Check className="mx-auto h-5 w-5 text-emerald-600"/> : <X className="mx-auto h-5 w-5 text-red-500"/>}</td>)}</tr>{rows.map((definition) => <tr key={definition.id} className="border-t"><th className="p-4 font-semibold">{definition.name}</th>{selected.map((service) => <td key={service.id} className="p-4 text-center">{display(valueFor(service, definition), definition)}</td>)}</tr>)}</tbody></table></div>}</section>
}
