import { Building2, ImagePlus, Save, Trash2 } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { updateMyCompany } from '../api/auth'
import { useAuth } from '../auth/useAuth'
import AccountNavigation from '../components/account/AccountNavigation'
import { Alert, Button, Card, PageHeader } from '../components/ui'

const Field = ({ label, wide, children, ...props }) => <label className={`block text-xs font-semibold text-slate-700 ${wide ? 'sm:col-span-2' : ''}`}>{label}{children || <input {...props} className="mt-1.5 h-11 w-full rounded-lg border bg-white px-3 text-sm font-normal outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10"/>}</label>

export default function CompanyProfilePage() {
  const { user, updateCurrentUser } = useAuth(); const fileRef = useRef(null)
  const [form, setForm] = useState({ company_name: '', company_logo_data: '', address: '', city: '', country: '' }); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => setForm({ company_name: user?.company_name || '', company_logo_data: user?.company_logo_data || '', address: user?.address || '', city: user?.city || '', country: user?.country || '' }), [user])
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  const image = (event) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; if (!['image/png', 'image/jpeg', 'image/webp'].includes(file.type) || file.size > 2 * 1024 * 1024) { setError('Choose a PNG, JPG, or WebP logo up to 2 MB.'); return } const reader = new FileReader(); reader.onload = () => set('company_logo_data', reader.result); reader.readAsDataURL(file) }
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const result = await updateMyCompany(form); updateCurrentUser(result.user); setMessage(result.message) } catch (err) { setError(err.message) } finally { setSaving(false) } }
  return <section><PageHeader eyebrow="Account" title="Company Profile" description="Keep the organization details shown across quotations and marketplace interactions accurate."/><div className="mt-6 grid gap-5 lg:grid-cols-[220px_minmax(0,720px)]"><AccountNavigation/><Card className="p-5 sm:p-6">{error && <Alert>{error}</Alert>}{message && <Alert tone="success">{message}</Alert>}<form onSubmit={save} className="mt-1"><div className="flex flex-col gap-4 border-b pb-6 sm:flex-row sm:items-center"><span className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-2xl border bg-slate-50">{form.company_logo_data ? <img src={form.company_logo_data} alt="Company logo" className="h-full w-full object-contain"/> : <Building2 className="h-7 w-7 text-slate-400"/>}</span><div><h2 className="text-sm font-semibold">Company logo</h2><p className="mt-1 text-xs text-slate-500">PNG, JPG or WebP, maximum 2 MB.</p><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="secondary" size="sm" icon={ImagePlus} onClick={() => fileRef.current?.click()}>Choose logo</Button>{form.company_logo_data && <Button type="button" variant="danger" size="sm" icon={Trash2} onClick={() => set('company_logo_data', '')}>Remove</Button>}</div><input ref={fileRef} onChange={image} type="file" accept="image/png,image/jpeg,image/webp" className="sr-only"/></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Company name" value={form.company_name} onChange={(event) => set('company_name', event.target.value)}/><Field label="Country" value={form.country} onChange={(event) => set('country', event.target.value)}/><Field label="City" value={form.city} onChange={(event) => set('city', event.target.value)}/><Field label="Business address" wide><textarea rows="4" value={form.address} onChange={(event) => set('address', event.target.value)} className="mt-1.5 w-full rounded-lg border bg-white p-3 text-sm font-normal outline-none focus:border-primary focus:ring-2 focus:ring-primary/10"/></Field></div><div className="mt-6 flex justify-end border-t pt-4"><Button type="submit" icon={Save} loading={saving}>Save company profile</Button></div></form></Card></div></section>
}
