import { ArrowLeft, Boxes, CheckCircle2, ChevronRight, Cpu, HardDrive, Search, Wrench } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link, Navigate, useParams, useSearchParams } from 'react-router-dom'
import { getMarketplaceCategories } from '../api/categories'
import { getMarketplaceServices } from '../api/marketplace'

const types = {
  software: { label: 'Software & SaaS', singular: 'software solution', description: 'Discover business software selected and published by verified marketplace vendors.', icon: Cpu, gradient: 'from-blue-700 via-blue-600 to-cyan-500' },
  hardware: { label: 'Hardware Solutions', singular: 'hardware solution', description: 'Compare business hardware, infrastructure and technology equipment from marketplace vendors.', icon: HardDrive, gradient: 'from-slate-800 via-blue-800 to-blue-500' },
  services: { label: 'Professional Services', singular: 'professional service', description: 'Find implementation, consulting, support and managed services offered by technology partners.', icon: Wrench, gradient: 'from-violet-700 via-indigo-600 to-blue-500' },
}

export default function ServiceTypePage() {
  const { type } = useParams(); const config = types[type]; const [params, setParams] = useSearchParams(); const [services, setServices] = useState([]); const [categories, setCategories] = useState([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const selectedCategory = params.get('category') || 'All'; const selectedSubcategory = params.get('subcategory') || 'All'
  useEffect(() => { if (!config) return; setLoading(true); Promise.all([getMarketplaceServices(), getMarketplaceCategories()]).then(([serviceRows, categoryRows]) => { setServices(serviceRows); setCategories(categoryRows) }).catch((requestError) => setError(requestError.message)).finally(() => setLoading(false)) }, [config, type])
  const products = useMemo(() => Object.values(services.filter((service) => service.service_type === type).reduce((all, service) => { const key = `${service.vendor_id}|${service.name}|${service.service_type}`; if (!all[key]) all[key] = { ...service, plans: [] }; all[key].plans.push(service); return all }, {})), [services, type])
  const categoryRows = useMemo(() => categories.map((category) => { const count = products.filter((product) => product.category?.name === category.name).length; const subcategories = (category.subcategories || []).map((subcategory) => ({ ...subcategory, count: products.filter((product) => product.subcategory?.name === subcategory.name).length })).filter((subcategory) => (subcategory.service_types || []).includes(type) || subcategory.count); return { ...category, count, subcategories } }).filter((category) => (category.service_types || []).includes(type) || category.subcategories.length || category.count), [categories, products, type])
  const activeCategory = categoryRows.find((category) => category.name === selectedCategory)
  const visible = products.filter((product) => (selectedCategory === 'All' || product.category?.name === selectedCategory) && (selectedSubcategory === 'All' || product.subcategory?.name === selectedSubcategory) && `${product.name} ${product.vendor?.company_name || ''} ${product.category?.name || ''} ${product.subcategory?.name || ''}`.toLowerCase().includes(query.trim().toLowerCase()))
  const selectCategory = (name) => { const next = new URLSearchParams(); if (name !== 'All') next.set('category', name); setParams(next) }
  const selectSubcategory = (name) => { const next = new URLSearchParams(); if (selectedCategory !== 'All') next.set('category', selectedCategory); if (name !== 'All') next.set('subcategory', name); setParams(next) }
  if (!config) return <Navigate to="/marketplace" replace/>
  const Icon = config.icon
  return <section className="pb-10"><div className={`overflow-hidden rounded-2xl bg-gradient-to-br ${config.gradient} text-white shadow-lg`}><div className="grid gap-8 px-6 py-9 sm:px-10 lg:grid-cols-[1fr_auto] lg:items-center lg:px-12"><div><Link to="/marketplace/solutions" className="inline-flex items-center gap-2 text-xs font-semibold text-white/80 hover:text-white"><ArrowLeft className="h-4 w-4"/>All solutions</Link><div className="mt-5 flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl border border-white/20 bg-white/15"><Icon className="h-7 w-7"/></span><div><p className="text-xs font-bold uppercase tracking-[.2em] text-white/70">Categories</p><h1 className="mt-1 text-3xl font-bold sm:text-4xl">{config.label}</h1></div></div><p className="mt-4 max-w-2xl text-sm leading-6 text-white/80">{config.description}</p></div><div className="rounded-2xl border border-white/20 bg-white/10 px-6 py-5 text-center"><p className="text-3xl font-bold">{products.length}</p><p className="mt-1 text-xs text-white/75">Available {products.length === 1 ? config.singular : `${config.singular}s`}</p></div></div></div>
    <nav aria-label="Breadcrumb" className="mt-5 flex flex-wrap items-center gap-2 text-xs text-slate-500"><Link to="/marketplace/solutions" className="hover:text-primary">All Solutions</Link><ChevronRight className="h-3.5 w-3.5"/><button onClick={() => selectCategory('All')} className="hover:text-primary">{config.label}</button>{selectedCategory !== 'All' && <><ChevronRight className="h-3.5 w-3.5"/><button onClick={() => selectSubcategory('All')} className="font-semibold hover:text-primary">{selectedCategory}</button></>}{selectedSubcategory !== 'All' && <><ChevronRight className="h-3.5 w-3.5"/><span className="font-semibold text-slate-900">{selectedSubcategory}</span></>}</nav>
    <div className="mt-4 rounded-2xl border bg-white p-5 shadow-subtle"><div className="flex flex-wrap gap-2"><button onClick={() => selectCategory('All')} className={`rounded-full px-4 py-2 text-xs font-semibold ${selectedCategory === 'All' ? 'bg-primary text-white' : 'bg-slate-100 text-slate-600 hover:bg-blue-50 hover:text-primary'}`}>All <span className="ml-1 opacity-70">{products.length}</span></button>{categoryRows.map((category) => <button key={category.id} disabled={!category.count} onClick={() => selectCategory(category.name)} className={`rounded-full px-4 py-2 text-xs font-semibold ${selectedCategory === category.name ? 'bg-primary text-white' : category.count ? 'bg-slate-100 text-slate-600 hover:bg-blue-50 hover:text-primary' : 'cursor-not-allowed bg-slate-50 text-slate-300'}`}>{category.name} <span className="ml-1 opacity-70">{category.count || 'Coming soon'}</span></button>)}</div>{activeCategory && <div className="mt-4 flex flex-wrap gap-2 border-t pt-4"><span className="mr-1 self-center text-[11px] font-bold uppercase tracking-wider text-slate-400">Subcategories</span><button onClick={() => selectSubcategory('All')} className={`rounded-lg px-3 py-2 text-xs font-semibold ${selectedSubcategory === 'All' ? 'bg-blue-50 text-primary' : 'text-slate-600 hover:bg-slate-100'}`}>All {activeCategory.name}</button>{activeCategory.subcategories.map((subcategory) => <button key={subcategory.id} disabled={!subcategory.count} onClick={() => selectSubcategory(subcategory.name)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${selectedSubcategory === subcategory.name ? 'bg-primary text-white' : subcategory.count ? 'bg-slate-100 text-slate-600 hover:bg-blue-50 hover:text-primary' : 'cursor-not-allowed bg-slate-50 text-slate-300'}`}>{subcategory.name} · {subcategory.count || 'Coming soon'}</button>)}</div>}</div>
    <div className="mt-6 flex flex-col gap-4 ui-toolbar shadow-subtle sm:flex-row sm:items-center"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${selectedSubcategory !== 'All' ? selectedSubcategory : selectedCategory !== 'All' ? selectedCategory : config.label.toLowerCase()}...`} className="h-11 w-full rounded-lg border pl-10 pr-3 text-sm outline-none focus:border-primary"/></div><div className="flex items-center gap-2 text-xs font-semibold text-slate-500"><CheckCircle2 className="h-4 w-4 text-emerald-500"/>{visible.length} verified result{visible.length === 1 ? '' : 's'}</div></div>
    {error && <p className="mt-6 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-600">{error}</p>}{loading ? <div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((item) => <div key={item} className="h-80 ui-skeleton rounded-xl"/>)}</div> : <div className="mt-6 grid items-stretch gap-5 sm:grid-cols-2 xl:grid-cols-3">{visible.map((product) => <Link to={`/marketplace/services/${product.id}`} key={product.id} className="group flex min-w-0 flex-col ui-table-shell transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-floating"><div className="grid h-48 place-items-center overflow-hidden border-b bg-gradient-to-br from-white to-slate-50 p-4">{product.images?.[0]?.image_url ? <img src={product.images[0].image_url} alt={product.name} className="h-full w-full object-contain transition group-hover:scale-105"/> : <Boxes className="h-11 w-11 text-primary/40"/>}</div><div className="flex flex-1 flex-col p-5"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-semibold text-primary">{product.subcategory?.name || product.category?.name || config.label}</span><span className="text-[11px] font-semibold text-slate-400">{product.plans.length} plan{product.plans.length === 1 ? '' : 's'}</span></div><h2 className="mt-3 min-h-10 text-base font-bold group-hover:text-primary">{product.name}</h2><p className="mt-1 text-xs text-slate-500">by {product.vendor?.company_name || product.vendor?.name || 'Verified vendor'}</p><p className="mt-auto pt-5 text-sm font-bold">{product.plans[0]?.price_from ? `Starting From $${Number(product.plans[0].price_from).toLocaleString()}` : 'Price on request'}</p></div></Link>)}{!visible.length && <div className="col-span-full grid min-h-64 place-items-center rounded-xl border border-dashed bg-white text-center"><div><Search className="mx-auto h-6 w-6 text-slate-300"/><h2 className="mt-3 text-sm font-bold">No matching solutions</h2><p className="mt-1 text-xs text-slate-500">Choose another available category or clear your search.</p></div></div>}</div>}
  </section>
}
