import { Building2, CalendarDays, Download, FileText, Mail, X } from 'lucide-react'
import useDialogAccessibility from '../../hooks/useDialogAccessibility'

export default function QuoteDocumentModal({ request, onClose }) {
  const dialogRef = useDialogAccessibility(true, onClose)
  const vendorName = request.vendor?.company_name || request.vendor?.name || 'Vendor'
  const customerName = request.user?.company_name || request.user?.name || 'Customer'
  const structuredItems = request.quote_data?.items || []
  const legacyLines = String(request.quote_message || '').split('\n').map((line) => line.trim()).filter(Boolean)
  const legacyItems = structuredItems.length ? [] : legacyLines.map((line) => { const match = line.match(/^(.+):\s*([\d.]+)\s*x\s*PKR\s*([\d,.]+)(?:\s*\+\s*([\d.]+)%\s*tax)?$/i); if (!match) return null; const quantity = Number(match[2]); const rate = Number(match[3].replaceAll(',', '')); const tax = Number(match[4] || 0); const amount = quantity * rate; return { name: match[1], description: '', quantity, rate, tax, amount, total: amount * (1 + tax / 100) } }).filter(Boolean)
  const items = structuredItems.length ? structuredItems : legacyItems
  const detailLines = legacyLines.filter((line) => !legacyItems.some((item) => line.startsWith(`${item.name}:`)))
  const subtotal = Number(request.quote_data?.subtotal ?? items.reduce((sum, item) => sum + Number(item.amount || 0), 0))
  const taxTotal = Number(request.quote_data?.tax_total ?? items.reduce((sum, item) => sum + Number(item.total || 0) - Number(item.amount || 0), 0))
  const discountAmount = Number(request.quote_data?.discount_amount || 0)
  return <div className="fixed inset-0 z-[100] overflow-y-auto bg-slate-950/65 p-3 backdrop-blur-sm sm:p-6 print:static print:bg-white print:p-0">
    <div ref={dialogRef} role="dialog" aria-modal="true" aria-label="Quotation document" className="mx-auto mb-8 max-w-4xl">
      <div className="mb-3 flex justify-end gap-2 print:hidden"><button type="button" onClick={() => window.print()} className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-xs font-bold text-white shadow"><Download className="h-4 w-4"/>Print / Save PDF</button><button type="button" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-lg bg-white text-slate-600 shadow"><X className="h-5 w-5"/></button></div>
      <article className="document-surface overflow-hidden rounded-2xl bg-white text-slate-900 shadow-overlay print:rounded-none print:shadow-none">
        <header className="bg-gradient-to-r from-[#082d66] to-primary px-6 py-7 text-white sm:px-10"><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-blue-100"><FileText className="h-4 w-4"/>Official Quotation</div><h1 className="mt-3 text-3xl font-bold">Quotation</h1><p className="mt-1 text-sm text-blue-100">RFQ #{request.id}</p></div><div className="rounded-xl border border-white/20 bg-white/10 px-5 py-3 text-right"><p className="text-[11px] uppercase text-blue-100">Total Amount</p><p className="mt-1 text-2xl font-bold">PKR {Number(request.quoted_price || 0).toLocaleString()}</p></div></div></header>
        <div className="p-6 sm:p-10">
          <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-[11px] font-bold uppercase text-slate-400">Quotation No.</p><p className="mt-1 text-sm font-bold">Q-{String(request.id).padStart(5, '0')}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[11px] font-bold uppercase text-slate-400">Quotation Date</p><p className="mt-1 text-sm font-bold">{new Date(request.quoted_at || request.created_at).toLocaleDateString()}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[11px] font-bold uppercase text-slate-400">Valid Until</p><p className="mt-1 text-sm font-bold">{request.quote_valid_until ? new Date(request.quote_valid_until).toLocaleDateString() : 'Not specified'}</p></div></div>
          <div className="mt-6 grid gap-4 sm:grid-cols-2"><section className="rounded-xl border p-5"><p className="text-[11px] font-bold uppercase tracking-wide text-primary">Quotation From</p><h2 className="mt-2 flex items-center gap-2 text-base font-bold"><Building2 className="h-4 w-4 text-primary"/>{vendorName}</h2>{request.vendor?.email && <p className="mt-2 flex items-center gap-2 text-xs text-slate-500"><Mail className="h-3.5 w-3.5"/>{request.vendor.email}</p>}</section><section className="rounded-xl border p-5"><p className="text-[11px] font-bold uppercase tracking-wide text-primary">Quotation For</p><h2 className="mt-2 flex items-center gap-2 text-base font-bold"><Building2 className="h-4 w-4 text-primary"/>{customerName}</h2>{request.user?.email && <p className="mt-2 flex items-center gap-2 text-xs text-slate-500"><Mail className="h-3.5 w-3.5"/>{request.user.email}</p>}</section></div>
          <section className="mt-6 overflow-x-auto rounded-xl border"><div className="grid min-w-[620px] grid-cols-[minmax(180px,2fr)_80px_110px_80px_120px] gap-3 bg-slate-900 px-5 py-3 text-[11px] font-bold text-white"><span>Item Details</span><span>Qty</span><span>Rate</span><span>Tax</span><span className="text-right">Line Total</span></div>{items.length ? items.map((item, index) => <div key={`${item.name}-${index}`} className="grid min-w-[620px] grid-cols-[minmax(180px,2fr)_80px_110px_80px_120px] gap-3 border-t px-5 py-4 text-xs"><div><h3 className="font-bold text-slate-900">{item.name}</h3>{item.description && <p className="mt-1 leading-5 text-slate-500">{item.description}</p>}</div><span>{Number(item.quantity).toLocaleString()}</span><span>PKR {Number(item.rate).toLocaleString()}</span><span>{Number(item.tax || 0)}%</span><strong className="text-right text-primary">PKR {Number(item.total).toLocaleString()}</strong></div>) : <div className="grid grid-cols-[1fr_150px] gap-4 p-5"><div><h3 className="text-sm font-bold">{request.service?.name || 'Requested solution'}</h3><p className="mt-2 whitespace-pre-wrap text-xs leading-6 text-slate-600">{request.quote_message || 'Formal quotation for the requested solution.'}</p></div><p className="text-right text-base font-bold text-primary">PKR {Number(request.quoted_price || 0).toLocaleString()}</p></div>}</section>
          {detailLines.length > 0 && <section className="mt-4 rounded-xl border p-5"><h3 className="text-xs font-bold uppercase tracking-wide text-slate-400">Vendor Notes</h3><p className="mt-2 whitespace-pre-wrap text-xs leading-6 text-slate-600">{detailLines.join('\n')}</p></section>}
          <div className="mt-6 flex justify-end"><div className="w-full max-w-sm rounded-xl bg-slate-50 p-5"><div className="space-y-2 border-b pb-4 text-xs"><div className="flex justify-between"><span>Subtotal</span><b>PKR {subtotal.toLocaleString()}</b></div><div className="flex justify-between"><span>Tax</span><b>PKR {taxTotal.toLocaleString()}</b></div>{discountAmount > 0 && <div className="flex justify-between text-emerald-600"><span>Discount</span><b>- PKR {discountAmount.toLocaleString()}</b></div>}</div><div className="mt-4 flex items-center justify-between text-lg font-bold"><span>Total (PKR)</span><span>PKR {Number(request.quoted_price || 0).toLocaleString()}</span></div></div></div>
          {request.quote_terms && <section className="mt-6 rounded-xl border p-5"><h3 className="text-sm font-bold">Terms and Conditions</h3><p className="mt-3 whitespace-pre-wrap text-xs leading-6 text-slate-600">{request.quote_terms}</p></section>}
          <footer className="mt-8 flex items-center justify-between border-t pt-5 text-[11px] text-slate-400"><span>Generated through Quotation Global Marketplace</span><span className="inline-flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5"/>{new Date().toLocaleDateString()}</span></footer>
        </div>
      </article>
    </div>
  </div>
}
