import { Check, ChevronDown, Search } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { countries } from '../../data/countries'

export default function CountrySelect({ value, onChange, required = false }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const root = useRef(null)
  useEffect(() => { if (!open) return undefined; const close = (event) => { if (!root.current?.contains(event.target)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [open])
  const filtered = useMemo(() => countries.filter((country) => country.toLowerCase().includes(query.trim().toLowerCase())), [query])
  return <div ref={root} className="relative"><button type="button" onClick={() => { setOpen(!open); setQuery('') }} className="flex h-11 w-full items-center rounded-md border bg-white px-3 text-left text-sm focus:border-primary"><span className={`min-w-0 flex-1 truncate ${value ? 'text-slate-900' : 'text-slate-400'}`}>{value || 'Select country'}</span><ChevronDown className={`h-4 w-4 text-slate-400 transition ${open ? 'rotate-180' : ''}`}/></button>{required && <input tabIndex="-1" aria-hidden="true" required value={value} onChange={() => {}} className="pointer-events-none absolute inset-0 -z-10 opacity-0"/>}{open && <div className="absolute bottom-12 left-0 z-50 w-full min-w-64 overflow-hidden rounded-lg border bg-white shadow-2xl"><label className="relative block border-b p-2"><Search className="absolute left-5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search country..." className="h-9 w-full rounded-md border pl-9 pr-3 text-xs outline-none focus:border-primary"/></label><div className="scrollbar-thin max-h-56 overflow-y-auto p-1">{filtered.map((country) => <button type="button" key={country} onClick={() => { onChange(country); setOpen(false) }} className={`flex w-full items-center rounded-md px-3 py-2 text-left text-xs hover:bg-blue-50 hover:text-primary ${country === value ? 'bg-blue-50 font-semibold text-primary' : 'text-slate-700'}`}><span className="flex-1">{country}</span>{country === value && <Check className="h-3.5 w-3.5"/>}</button>)}{!filtered.length && <p className="p-5 text-center text-xs text-slate-400">No country found.</p>}</div></div>}</div>
}
